title: "Klara Brabec Wagnerova"
baseurl: "/klaras-website"

languages:
  en:
    name: "English"
    default: true
  cz:
    name: "Čeština"

collections:
  novels:
  poems:

defaults:
  - scope:
      path: "**/cz"
    values:
      language: "cz"
  - scope:
      path: "**/en"
    values:
      language: "en"
  - scope:
      path: "/novels"
    values:
      layout: "novel"
  - scope:
      path: "/poems"
    values:
      layout: "poem"
  - scope:
      path: ""
    values:
      layout: "default"